before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - ROLLBAR_TOKEN={{ secrets.ROLLBAR_TOKEN }}
      - TELEGRAM_APITOKEN={{ secrets.TELEGRAM_APITOKEN }}
      - SPOTIFY_ID={{ secrets.SPOTIFY_ID }}
      - SPOTIFY_SECRET={{ secrets.SPOTIFY_SECRET }}
    goos:
      - linux
      - windows
archives:
  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'